#!/bin/bash

set -e
supported_languages="cs_CZ"
root="`dirname \"$0\"`/.."
cd $root
wp i18n make-pot . i18n/wmcz-theme.pot
sed -n '1p;2p' i18n/wmcz-theme.pot > /tmp/$$
echo "#, fuzzy" >> /tmp/$$
sed '1d;2d' i18n/wmcz-theme.pot >> /tmp/$$
mv /tmp/$$ i18n/wmcz-theme.pot

exit 0

# This will regenerate lang-specific files, which is not desired since we're TWN-integrated
cd i18n
for lang in $supported_languages; do
	in=wmcz-theme-$lang.po
	if [ -f $in ]; then
		msgmerge --backup=off --update wmcz-theme-$lang.po wmcz-theme.pot
	else
		msginit -o $in --locale=$lang --no-translator
	fi
done
